### ISSUE TITLE
textarea 禁止缩放

### ISSUE THREAD

**Issue by Daotin** [Daotin/fe-blog#200]
```css
textarea {
    resize: none; // 禁止拖动
    resize: vertical; // 可以上下拖动
    resize: horizontal; // 可以左右拖动
}
```
